version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/careernus
      - DEBUG=True
      - SECRET_KEY=dev_secret_key_change_in_production
    depends_on:
      - db
    
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=careernus
    ports:
      - "5432:5432"

volumes:
  postgres_data:
