"""Add user authentication

Revision ID: 7d20c6612478
Revises: 0ac318ce8d12
Create Date: 2025-06-05 03:42:13.235491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d20c6612478'
down_revision = '0ac318ce8d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
